# Generated by Django 3.1.7 on 2022-06-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0001_initial"), ("document", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="documenttemplate", old_name="file", new_name="document"
        ),
        migrations.AddField(
            model_name="generateddocument",
            name="generated_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.userprofile",
            ),
            preserve_default=False,
        ),
    ]
